name: "Deploy Application"
on: 
  push:
    branches:
      - main
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: script
        id: runtask
        run: |
            echo "hello world"
      





            
            